from .cities import CityListSerializer, CityCreateSerializer, CityDetailSerializer, CityUpdateSerializer
from .countries import CountryListSerializer, CountryCreateSerializer, CountryDetailSerializer, CountryUpdateSerializer
from .regions import RegionListSerializer, RegionCreateSerializer, RegionDetailSerializer, RegionUpdateSerializer
from .address import AddressListSerializer, AddressDetailSerializer, AddressUpdateSerializer, AddressCreateSerializer
